.TH "SALAHTIME" "1" "" "Unix Sheikh" ""
.SH "NAME"
salahtime \- displays the Islamic prayer time for Copenhagen in Denmark
.SH "SYNOPSIS"
.B salahtime
[\fB\min\fR]
.SH OPTIONS
.TP
.B n
The optional number of minutes to modify the time. Default is 0.
.SH "DESCRIPTION"
Without any additional input salahtime will display the prayer times without daylight saving time following the Islamic school of thought of Imam Shafi'i (rha).

salahtime does not calculate or display the time of asr by other views because there is great difference of opinion within the Hanafi school about the time of asr. This is due to the fact that both of Abu Hanifa's main students, Qadi Abu Yusuf and Muhammad ibn al-Hasan, held asr to come in at one shadow length, contrary to their teacher's position of two shadow lengths. Hence, Muslims who follow any of these views know what to add to the time of asr when looking at a time table from the Shafi'i school of thought.

.nf
$ salahtime

Date today 01/01-2018

---------------------
Fajr:           06:40
Shuruk:         08:37
Dhuhr:          12:15
Asr:            13:35
Maghrib:        15:51
Isha:           17:41
---------------------

Time is now:    13:25
.fi

You can change to daylight saving time by adding an hour (specified in minutes):

.nf
$ salahtime 60
.fi

If your city isn't Copenhagen, but a city close by like Århus, you can also account for that by adding the extra 9 minutes.

.nf
$ salahtime 69
.fi

You can also subtract time if you need to do that:

.nf
$ salahtime -5
.fi

.SH "NOTE"

If you want to avoid having to add the number "60" during daylight savings you can create a simple alias and put that into your shell script profile:

.nf
alias salahtime='salahtime 60'
.fi

Currently the maximum amount of minutes you can add or subtract are 120 minutes.

.SH "FILES"

.nf
salahtime 
salahtime.1
.fi

.SH "AUTHOR"
Unix Sheikh
